// Generated by gencpp from file drone/GridTx.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_GRIDTX_H
#define DRONE_MESSAGE_GRIDTX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct GridTx_
{
  typedef GridTx_<ContainerAllocator> Type;

  GridTx_()
    : d1(0)
    , d2(0)
    , data(0)  {
    }
  GridTx_(const ContainerAllocator& _alloc)
    : d1(0)
    , d2(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef int64_t _d1_type;
  _d1_type d1;

   typedef int64_t _d2_type;
  _d2_type d2;

   typedef int64_t _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::drone::GridTx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::GridTx_<ContainerAllocator> const> ConstPtr;

}; // struct GridTx_

typedef ::drone::GridTx_<std::allocator<void> > GridTx;

typedef boost::shared_ptr< ::drone::GridTx > GridTxPtr;
typedef boost::shared_ptr< ::drone::GridTx const> GridTxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::GridTx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::GridTx_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'drone': ['/home/mvp/Desktop/testnavi/src/drone/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drone::GridTx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::GridTx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::GridTx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::GridTx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::GridTx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::GridTx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::GridTx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e305bbdd6154480a44d99b1135a2c2dd";
  }

  static const char* value(const ::drone::GridTx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe305bbdd6154480aULL;
  static const uint64_t static_value2 = 0x44d99b1135a2c2ddULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::GridTx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/GridTx";
  }

  static const char* value(const ::drone::GridTx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::GridTx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 d1\n\
int64 d2\n\
int64 data\n\
";
  }

  static const char* value(const ::drone::GridTx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::GridTx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.d1);
      stream.next(m.d2);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridTx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::GridTx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone::GridTx_<ContainerAllocator>& v)
  {
    s << indent << "d1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d1);
    s << indent << "d2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d2);
    s << indent << "data: ";
    Printer<int64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_GRIDTX_H
