// Generated by gencpp from file drone/NavSatFix.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_NAVSATFIX_H
#define DRONE_MESSAGE_NAVSATFIX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct NavSatFix_
{
  typedef NavSatFix_<ContainerAllocator> Type;

  NavSatFix_()
    : longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)  {
    }
  NavSatFix_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _altitude_type;
  _altitude_type altitude;




  typedef boost::shared_ptr< ::drone::NavSatFix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::NavSatFix_<ContainerAllocator> const> ConstPtr;

}; // struct NavSatFix_

typedef ::drone::NavSatFix_<std::allocator<void> > NavSatFix;

typedef boost::shared_ptr< ::drone::NavSatFix > NavSatFixPtr;
typedef boost::shared_ptr< ::drone::NavSatFix const> NavSatFixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::NavSatFix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::NavSatFix_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'drone': ['/home/mvp/Desktop/testnavi/src/drone/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drone::NavSatFix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::NavSatFix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::NavSatFix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::NavSatFix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::NavSatFix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::NavSatFix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::NavSatFix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6ce0a2191bc628a283cd615ab04a4d1";
  }

  static const char* value(const ::drone::NavSatFix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6ce0a2191bc628aULL;
  static const uint64_t static_value2 = 0x283cd615ab04a4d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::NavSatFix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/NavSatFix";
  }

  static const char* value(const ::drone::NavSatFix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::NavSatFix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 longitude\n\
float64 latitude\n\
float64 altitude\n\
";
  }

  static const char* value(const ::drone::NavSatFix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::NavSatFix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavSatFix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::NavSatFix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone::NavSatFix_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_NAVSATFIX_H
