// Generated by gencpp from file drone/GPS_Coord.msg
// DO NOT EDIT!


#ifndef DRONE_MESSAGE_GPS_COORD_H
#define DRONE_MESSAGE_GPS_COORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone
{
template <class ContainerAllocator>
struct GPS_Coord_
{
  typedef GPS_Coord_<ContainerAllocator> Type;

  GPS_Coord_()
    : longitude(0.0)
    , latitude(0.0)
    , height(0.0)  {
    }
  GPS_Coord_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::drone::GPS_Coord_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone::GPS_Coord_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_Coord_

typedef ::drone::GPS_Coord_<std::allocator<void> > GPS_Coord;

typedef boost::shared_ptr< ::drone::GPS_Coord > GPS_CoordPtr;
typedef boost::shared_ptr< ::drone::GPS_Coord const> GPS_CoordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone::GPS_Coord_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone::GPS_Coord_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'drone': ['/home/hello/testnavi/src/drone/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drone::GPS_Coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone::GPS_Coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::GPS_Coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone::GPS_Coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::GPS_Coord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone::GPS_Coord_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone::GPS_Coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e62768fc20577eb4d6831142c7af4bea";
  }

  static const char* value(const ::drone::GPS_Coord_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe62768fc20577eb4ULL;
  static const uint64_t static_value2 = 0xd6831142c7af4beaULL;
};

template<class ContainerAllocator>
struct DataType< ::drone::GPS_Coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone/GPS_Coord";
  }

  static const char* value(const ::drone::GPS_Coord_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone::GPS_Coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 longitude\n\
float64 latitude\n\
float64 height\n\
";
  }

  static const char* value(const ::drone::GPS_Coord_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone::GPS_Coord_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_Coord_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone::GPS_Coord_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone::GPS_Coord_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MESSAGE_GPS_COORD_H
